language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
services:
  - mongodb
before_script:
  - npm install -g mocha
  - npm install -g grunt-cli
sudo:
  - false
notifications:
  email:
    - travis.mchattie@thinksolid.com
    - peter.ajtai@thinksolid.com
    - cooper.hilscher@thinksolid.com
    - greg.larrenaga@thinksolid.com
    - kaija.rayne@thinksolid.com
    - eric.beringer@thinksolid.com
