language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    - travis.mchattie@thinksolid.com
    - peter.ajtai@thinksolid.com
    - cooper.hilscher@thinksolid.com
    - greg.larrenaga@thinksolid.com
    - kaija.rayne@thinksolid.com
